create table ACTIVECODE
(
    ACTIVECODE_ID INTEGER           not null
        primary key,
    GAMECODE_ID   INTEGER
        constraint FKFPFAYFKHQKFTM1E9FSQFHFXKQ
            references GAMECODE,
    USER_ID       INTEGER
        constraint FK8YO35B17CLLIQ9RDP3IABQBHR
            references PLATFORM_USER,
    VERSION       INTEGER default 0 not null
);

INSERT INTO APP.ACTIVECODE (ACTIVECODE_ID, GAMECODE_ID, USER_ID, VERSION) VALUES (911, 825, 217, 0);
INSERT INTO APP.ACTIVECODE (ACTIVECODE_ID, GAMECODE_ID, USER_ID, VERSION) VALUES (913, 863, 217, 0);
INSERT INTO APP.ACTIVECODE (ACTIVECODE_ID, GAMECODE_ID, USER_ID, VERSION) VALUES (932, 836, 1, 0);
INSERT INTO APP.ACTIVECODE (ACTIVECODE_ID, GAMECODE_ID, USER_ID, VERSION) VALUES (936, 837, 425, 0);
INSERT INTO APP.ACTIVECODE (ACTIVECODE_ID, GAMECODE_ID, USER_ID, VERSION) VALUES (1034, 895, 217, 0);
INSERT INTO APP.ACTIVECODE (ACTIVECODE_ID, GAMECODE_ID, USER_ID, VERSION) VALUES (1305, 855, 1132, 0);
INSERT INTO APP.ACTIVECODE (ACTIVECODE_ID, GAMECODE_ID, USER_ID, VERSION) VALUES (1310, 858, 1306, 0);
