create table CATEGORY
(
    CATEGORY_ID  INTEGER           not null
        primary key,
    CATEGORYNAME VARCHAR(255),
    DESCRIPTION  VARCHAR(255),
    VERSION      INTEGER default 0 not null
);

INSERT INTO APP.CATEGORY (CATEGORY_ID, CATEGORYNAME, DESCRIPTION, VERSION) VALUES (8, 'zręcznościowe', 'other', 0);
INSERT INTO APP.CATEGORY (CATEGORY_ID, CATEGORYNAME, DESCRIPTION, VERSION) VALUES (9, 'przygodowe', 'other', 0);
INSERT INTO APP.CATEGORY (CATEGORY_ID, CATEGORYNAME, DESCRIPTION, VERSION) VALUES (10, 'fabularne', 'other', 0);
INSERT INTO APP.CATEGORY (CATEGORY_ID, CATEGORYNAME, DESCRIPTION, VERSION) VALUES (11, 'sportowe', 'other', 0);
INSERT INTO APP.CATEGORY (CATEGORY_ID, CATEGORYNAME, DESCRIPTION, VERSION) VALUES (12, 'strategiczne', 'other', 0);
INSERT INTO APP.CATEGORY (CATEGORY_ID, CATEGORYNAME, DESCRIPTION, VERSION) VALUES (13, 'symulacyjne', 'other', 0);
INSERT INTO APP.CATEGORY (CATEGORY_ID, CATEGORYNAME, DESCRIPTION, VERSION) VALUES (826, 'akcji', 'other', 0);
INSERT INTO APP.CATEGORY (CATEGORY_ID, CATEGORYNAME, DESCRIPTION, VERSION) VALUES (1316, 'wyścigowe', 'other', 0);
