create table GAME
(
    GAME_ID     INTEGER           not null
        primary key,
    GAMENAME    VARCHAR(255),
    IMAGE       VARCHAR(255),
    ISPOLISH    BOOLEAN           not null,
    PRICE       DECIMAL(19, 2),
    SIZEGB      DOUBLE            not null,
    CATEGORY_ID INTEGER
        constraint FKGCGX2LIG7O3NBPO3JI8DKRBO2
            references CATEGORY,
    VERSION     INTEGER default 0 not null
);

INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (725, 'cod1', 'cod.png', true, 210.80, 300.7, 11, 0);
INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (827, 'cod2', 'cod.png', true, 400.91, 1205.2, 826, 0);
INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (828, 'cod3', 'cod.png', false, 602.20, 135.2, 8, 0);
INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (829, 'cod4', 'cod.png', true, 102.73, 400, 13, 0);
INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (830, 'cod5', 'cod.png', false, 1000.99, 271.3, 12, 0);
INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (831, 'cod10', 'cod.png', true, 2501.98, 900.9, 11, 0);
INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (832, 'cod11', 'cod.png', false, 3211.11, 240.91, 9, 0);
INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (833, 'cod15', 'cod.png', true, 141.99, 88.78, 8, 0);
INSERT INTO APP.GAME (GAME_ID, GAMENAME, IMAGE, ISPOLISH, PRICE, SIZEGB, CATEGORY_ID, VERSION) VALUES (1313, 'ModernGame', 'cod.png', true, 350.99, 127.8, 8, 0);
