create table INDIVIDUALUSER
(
    FIRSTNAME VARCHAR(255),
    LASTNAME  VARCHAR(255),
    USER_ID   INTEGER not null
        primary key
        constraint FKBNSVO3DGYLN3SOCQPGJDR3THL
            references PLATFORM_USER
);

INSERT INTO APP.INDIVIDUALUSER (FIRSTNAME, LASTNAME, USER_ID) VALUES ('A', 'M', 1);
INSERT INTO APP.INDIVIDUALUSER (FIRSTNAME, LASTNAME, USER_ID) VALUES ('a', 'm', 425);
INSERT INTO APP.INDIVIDUALUSER (FIRSTNAME, LASTNAME, USER_ID) VALUES ('N', 'A', 525);
INSERT INTO APP.INDIVIDUALUSER (FIRSTNAME, LASTNAME, USER_ID) VALUES ('T', 'N', 1132);
