create table PLATFORM_USER
(
    USER_ID  INTEGER           not null
        primary key,
    EMAIL    VARCHAR(255),
    MONEY    DECIMAL(19, 2),
    PASSWORD VARCHAR(255),
    USERNAME VARCHAR(255),
    VERSION  INTEGER default 0 not null
);

INSERT INTO APP.PLATFORM_USER (USER_ID, EMAIL, MONEY, PASSWORD, USERNAME, VERSION) VALUES (1, 'a@o2.pl', 9071.20, 'a', 'Nowy', 0);
INSERT INTO APP.PLATFORM_USER (USER_ID, EMAIL, MONEY, PASSWORD, USERNAME, VERSION) VALUES (217, 'game1111@o2.pl', 5953.11, 'b', 'GameDev', 5);
INSERT INTO APP.PLATFORM_USER (USER_ID, EMAIL, MONEY, PASSWORD, USERNAME, VERSION) VALUES (425, 'a@o2.pl', 9789.20, 'a', 'AM', 0);
INSERT INTO APP.PLATFORM_USER (USER_ID, EMAIL, MONEY, PASSWORD, USERNAME, VERSION) VALUES (525, 'new@o2.pl', 9699.20, 'a', 'Nowy2', 0);
INSERT INTO APP.PLATFORM_USER (USER_ID, EMAIL, MONEY, PASSWORD, USERNAME, VERSION) VALUES (1132, 'tn@example.com', 6691.42, 'abc', 'User', 4);
INSERT INTO APP.PLATFORM_USER (USER_ID, EMAIL, MONEY, PASSWORD, USERNAME, VERSION) VALUES (1306, 'newcompany@example.com', 8795.60, 'abc', 'Firma', 2);
