create table USERTOURNAMENT
(
    USERTOURNAMENT_ID INTEGER           not null
        primary key,
    ACCESSCODE        VARCHAR(255),
    TOURNAMENT_ID     INTEGER
        constraint FKQAOWNRUTVWPU0U8SKB4C2QA0P
            references TOURNAMENT,
    USER_ID           INTEGER
        constraint FKHFT3IV5VXXU3N1HM7MUO2RT44
            references PLATFORM_USER,
    VERSION           INTEGER default 0 not null
);

INSERT INTO APP.USERTOURNAMENT (USERTOURNAMENT_ID, ACCESSCODE, TOURNAMENT_ID, USER_ID, VERSION) VALUES (933, 'RWDfwIz2E754V4s', 914, 1, 0);
INSERT INTO APP.USERTOURNAMENT (USERTOURNAMENT_ID, ACCESSCODE, TOURNAMENT_ID, USER_ID, VERSION) VALUES (937, 'QNwjWE1W5cPiwIN', 914, 425, 0);
INSERT INTO APP.USERTOURNAMENT (USERTOURNAMENT_ID, ACCESSCODE, TOURNAMENT_ID, USER_ID, VERSION) VALUES (1312, 'KrkqCQPfjQmcSSJ', 1311, 1132, 0);
